[2023-05-26T10:27:31.365+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=manual__2023-05-26T10:27:22.355038+00:00/task_id=from_local_to_gcs_task_2016 permission to 509
[2023-05-26T10:27:31.403+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=manual__2023-05-26T10:27:22.355038+00:00/task_id=from_local_to_gcs_task_2016 permission to 509
[2023-05-26T10:27:31.437+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_data_gcs_dag.from_local_to_gcs_task_2016 manual__2023-05-26T10:27:22.355038+00:00 [queued]>
[2023-05-26T10:27:31.449+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_data_gcs_dag.from_local_to_gcs_task_2016 manual__2023-05-26T10:27:22.355038+00:00 [queued]>
[2023-05-26T10:27:31.450+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-05-26T10:27:31.478+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): from_local_to_gcs_task_2016> on 2023-05-26 10:27:22.355038+00:00
[2023-05-26T10:27:31.486+0000] {standard_task_runner.py:57} INFO - Started process 106 to run task
[2023-05-26T10:27:31.491+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_gcs_dag', 'from_local_to_gcs_task_2016', 'manual__2023-05-26T10:27:22.355038+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data_gcs_dag.py', '--cfg-path', '/tmp/tmpvjnn8g7v']
[2023-05-26T10:27:31.495+0000] {standard_task_runner.py:85} INFO - Job 109: Subtask from_local_to_gcs_task_2016
[2023-05-26T10:27:31.557+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=manual__2023-05-26T10:27:22.355038+00:00/task_id=from_local_to_gcs_task_2016 permission to 509
[2023-05-26T10:27:31.567+0000] {task_command.py:410} INFO - Running <TaskInstance: ingest_data_gcs_dag.from_local_to_gcs_task_2016 manual__2023-05-26T10:27:22.355038+00:00 [running]> on host e663fcea502a
[2023-05-26T10:27:31.671+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_data_gcs_dag' AIRFLOW_CTX_TASK_ID='from_local_to_gcs_task_2016' AIRFLOW_CTX_EXECUTION_DATE='2023-05-26T10:27:22.355038+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-26T10:27:22.355038+00:00'
[2023-05-26T10:27:31.742+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data_gcs_dag.py", line 45, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 2682, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/Horticulture_2016.parquet'
[2023-05-26T10:27:31.760+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_data_gcs_dag, task_id=from_local_to_gcs_task_2016, execution_date=20230526T102722, start_date=20230526T102731, end_date=20230526T102731
[2023-05-26T10:27:31.794+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 109 for task from_local_to_gcs_task_2016 ([Errno 2] No such file or directory: '/opt/airflow/Horticulture_2016.parquet'; 106)
[2023-05-26T10:27:31.824+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-05-26T10:27:31.856+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
