[2023-05-26T10:27:26.968+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=manual__2023-05-26T10:27:22.355038+00:00/task_id=csv_to_parquet_2016 permission to 509
[2023-05-26T10:27:27.022+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=manual__2023-05-26T10:27:22.355038+00:00/task_id=csv_to_parquet_2016 permission to 509
[2023-05-26T10:27:27.063+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ingest_data_gcs_dag.csv_to_parquet_2016 manual__2023-05-26T10:27:22.355038+00:00 [queued]>
[2023-05-26T10:27:27.079+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ingest_data_gcs_dag.csv_to_parquet_2016 manual__2023-05-26T10:27:22.355038+00:00 [queued]>
[2023-05-26T10:27:27.080+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2023-05-26T10:27:27.099+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): csv_to_parquet_2016> on 2023-05-26 10:27:22.355038+00:00
[2023-05-26T10:27:27.109+0000] {standard_task_runner.py:57} INFO - Started process 92 to run task
[2023-05-26T10:27:27.116+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ingest_data_gcs_dag', 'csv_to_parquet_2016', 'manual__2023-05-26T10:27:22.355038+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/ingest_data_gcs_dag.py', '--cfg-path', '/tmp/tmpsbuq0cy3']
[2023-05-26T10:27:27.120+0000] {standard_task_runner.py:85} INFO - Job 104: Subtask csv_to_parquet_2016
[2023-05-26T10:27:27.196+0000] {logging_mixin.py:149} INFO - Changing /opt/***/logs/dag_id=ingest_data_gcs_dag/run_id=manual__2023-05-26T10:27:22.355038+00:00/task_id=csv_to_parquet_2016 permission to 509
[2023-05-26T10:27:27.206+0000] {task_command.py:410} INFO - Running <TaskInstance: ingest_data_gcs_dag.csv_to_parquet_2016 manual__2023-05-26T10:27:22.355038+00:00 [running]> on host e663fcea502a
[2023-05-26T10:27:27.345+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ingest_data_gcs_dag' AIRFLOW_CTX_TASK_ID='csv_to_parquet_2016' AIRFLOW_CTX_EXECUTION_DATE='2023-05-26T10:27:22.355038+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-26T10:27:22.355038+00:00'
[2023-05-26T10:27:27.349+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_data_gcs_dag.py", line 29, in convert_csv_to_parquet
    df = pd.read_csv(f"{path_to_local_home}/{file_csv}")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/Horticulture_2016.csv'
[2023-05-26T10:27:27.366+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=ingest_data_gcs_dag, task_id=csv_to_parquet_2016, execution_date=20230526T102722, start_date=20230526T102727, end_date=20230526T102727
[2023-05-26T10:27:27.388+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 104 for task csv_to_parquet_2016 ([Errno 2] No such file or directory: '/opt/airflow/Horticulture_2016.csv'; 92)
[2023-05-26T10:27:27.408+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-05-26T10:27:27.430+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
